name: Bitholla
favicon: null
layout_spectrum: 0.09414620534516871
typography_spectrum: 0.18055123556405306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.07007447839714587
  lightness: 0.4094774005934596
  saturation: 0.2576236475724727
  rhythmicContrast: 0.4972771343309432
purpose: []
